# Header
menu:
  首页: /
  友链: /links
  留言: /messages
  关于: /about
  アニメ: /anime
# logo: https://qiniu.miiiku.xyz/src/images/logo.png
banner: https://cloud.miiiku.xyz/src/images/banner-6.jpg-compress
# banner: css/images/banner.jpg

# large cover
large_legnth: 20

# 一言
# docs: https://hitokoto.cn/api
# type: [a, b, c, d, e, f, g]
hitokoto:
  enable: false
  type: a

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn
# 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
valine:
  enable: false
  appId: oTmfgIaoB7PfPATvA9tsOwTu-gzGzoHsz
  appKey: PPbJycuezKD3BJlhHUy8zOnG
  avatar: mm
  placeholder: 随便说点什么叭～
  notify: true
  visitor: true
  pageSize: 10

disqus:
  enable: true
  website: sukoshi95
  error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# waterfall 瀑布流
# docs: https://github.com/miiiku/waterfall
# Specific configuration information go to `layout/plug-in/waterfall.ejs`
waterfall:
  enable: true

# zoom 图片预览
# docs: https://github.com/miiiku/zoom
# Specific configuration information go to `layout/plug-in/zoom.ejs`
zoom:
  enable: true

# widget behavior
archive_type: 'monthly'
show_count: false

# beian
beian: 蜀ICP备15014309号

# Miscellaneous
google_analytics: UA-165681463-1
gauges_analytics: 
baidu_analytics: ad36dfdc108f5a5ffcab702be06a0ad7
tencent_analytics: 66537616
favicon: /favicon.ico


# Social Icon
social_icon:
  header_enable: true
  footer_enable: true
  icons:
    - { type: twitter,    value: https://twitter.com/guanquanhong }
    - { type: weibo,      value: https://weibo.com/5561168966/profile?rightmod=1&wvr=6&mod=personinfo }
    - { type: github,     value: https://github.com/miiiku/ }
    - { type: ins,        value: }
    - { type: zhihu,      value: }
    - { type: email,      value: }
    - { type: google+,    value: }
    - { type: youtube,    value: }
    - { type: cloudmusic, value: }